# Generated by Django 6.0.6 on 2026-06-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('content', models.TextField(verbose_name='Тип контенту')),
                ('published_date', models.DateTimeField()),
            ],
        ),
    ]
